server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: pricetracker
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: ${PORT:8080}

logging:
  level:
    root: error